/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.acme.gui;

import br.com.acme.AcademicLibrary;
import br.com.acme.Article;
import br.com.acme.Author;
import br.com.acme.Journal;
import br.com.acme.Publication;
import br.com.acme.logic.ALManager;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hibiscus, Vinicios, gabid
 */
public class ListArticlesForm extends javax.swing.JDialog {

    private AcademicLibrary library;

    /**
     * Creates new form ListArticlesForm
     */
    public ListArticlesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        library = ALManager.getInstance();

        populateTable();
    }

    /**
     * Coloca na tela todos os articles.
     */
    private void populateTable() {
        jlTotal.setText(String.valueOf(library.countArticles()));

        DefaultTableModel model = (DefaultTableModel) jtArticleList.getModel();
        model.setRowCount(0);

        ArrayList<Article> articlesList = library.getAllArticles();

        int line = 0;
        for (Article a : articlesList) {

            String authorName = "";
            for (Author aut : a.getAuthors()) {
                authorName = authorName + aut.getName();
            }

            ArrayList<String> keyWords = a.getKeyWords();
            String s = "";
            for (String k : keyWords) {
                s = s + k + ", ";
            }
            Journal j = a.getJournal();

            // Joga os dados na tabela.
            model.addRow(new Object[]{a.getTitle(), authorName, a.getYear(), a.getVolume(),
                keyWords, a.getIssn(), a.getStartPage() + "-" + a.getEndPage(), a.getJournal().getName(),
                j.getImpactFactor(), j.getPublisher().getName(), j.getPublisher().getCountry()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jspArticleList = new javax.swing.JScrollPane();
        jtArticleList = new javax.swing.JTable();
        jbClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jbPrintArticleList = new javax.swing.JButton();
        jbRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List of Articles");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Articles in your library");

        jtArticleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Authors", "Year", "Volume", "Keywords", "ISSN", "Pages", "Journal", "Impact Factor", "Publisher", "Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Byte.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspArticleList.setViewportView(jtArticleList);

        jbClose.setText("Close");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Total:");

        jlTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jbPrintArticleList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jtb/printer.png"))); // NOI18N
        jbPrintArticleList.setText("Print");
        jbPrintArticleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintArticleListActionPerformed(evt);
            }
        });

        jbRemove.setText("Remove Selected");
        jbRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(359, 359, 359)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbRemove)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbPrintArticleList)
                                .addComponent(jspArticleList, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbPrintArticleList)))
                .addGap(18, 18, 18)
                .addComponent(jspArticleList, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRemove)
                    .addComponent(jbClose))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1036, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jbCloseActionPerformed

    private void jbPrintArticleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintArticleListActionPerformed
        try {
            MessageFormat title = new MessageFormat("Library Articles");
            MessageFormat footer = new MessageFormat("UNIJUI - Computer Science 2018");
            jtArticleList.print(JTable.PrintMode.FIT_WIDTH, title, footer);
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, "An error occurred while printing the articles informations. Try again  \n Error: " + ex);
        }

    }//GEN-LAST:event_jbPrintArticleListActionPerformed

    private void jbRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveActionPerformed
        TableModel model = jtArticleList.getModel();

        DefaultTableModel tm = (DefaultTableModel) jtArticleList.getModel();
        long selectedArticle = (long) model.getValueAt(jtArticleList.getSelectedRow(), 5); // Pega o issn da linha selecionada.

        library.removeArticle(selectedArticle);
        tm.removeRow(jtArticleList.getSelectedRow());
        populateTable();
    }//GEN-LAST:event_jbRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbPrintArticleList;
    private javax.swing.JButton jbRemove;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JScrollPane jspArticleList;
    private javax.swing.JTable jtArticleList;
    // End of variables declaration//GEN-END:variables
}
